version: '3.3'

services:
  node:
    container_name: node

    build:
      context: .
      dockerfile: ./docker/node/Dockerfile

    ports:
      - 3000:3000

    volumes:
      - ./app/node:/app

    tty: true
